// src/routes/admin/tickets/[id]/+page.svelte
<script lang="ts">
	import { page } from '$app/state';
	import * as Accordion from '$lib/components/ui/accordion';
	import { Badge } from '$lib/components/ui/badge';
	import { Button } from '$lib/components/ui/button';
	import { Label } from '$lib/components/ui/label';
	import { ScrollArea } from '$lib/components/ui/scroll-area';
	import * as Select from '$lib/components/ui/select';
	import { Skeleton } from '$lib/components/ui/skeleton';
	import { Building, ChevronLeft, Home as HomeIcon, Send, User, UserCheck } from 'lucide-svelte';
	import { toast } from 'svelte-sonner';
	import { getTicket, sendTicketMessage, updateTicketStatus } from '../tickets.remote';

	const id = $derived(page.params.id ?? '');
	let dataPromise = $derived(getTicket(id));

	let messageContent = $state('');

	async function handleSendMessage() {
		if (!messageContent.trim()) return;
		try {
			await sendTicketMessage({ ticketId: id, content: messageContent });
			messageContent = '';
			await dataPromise.refresh();
		} catch (e: any) {
			toast.error(e.message || 'Failed to send message');
		}
	}

	async function updateStatus(status: any) {
		try {
			await updateTicketStatus({ id, status });
			toast.success(`Status updated to ${status}`);
			await dataPromise.refresh();
		} catch (e: any) {
			toast.error(e.message || 'Failed to update status');
		}
	}

	async function updatePriority(priority: any) {
		try {
			// updateTicketStatus also accepts priority
			await updateTicketStatus({ id, status: (await dataPromise).status as any, priority });
			toast.success(`Priority updated to ${priority}`);
			await dataPromise.refresh();
		} catch (e: any) {
			toast.error(e.message || 'Failed to update priority');
		}
	}

	const statusColors: Record<string, string> = {
		open: 'bg-blue-500/10 text-blue-500 border-blue-500/20',
		in_progress: 'bg-amber-500/10 text-amber-500 border-amber-500/20',
		resolved: 'bg-green-500/10 text-green-500 border-green-500/20',
		closed: 'bg-slate-500/10 text-slate-500 border-slate-500/20'
	};
</script>

<div class="flex flex-col h-full bg-slate-50/50 dark:bg-slate-950/50">
	<header class="flex items-center gap-4 border-b bg-background px-6 py-4 shrink-0">
		<Button variant="ghost" size="icon" href="/admin/tickets">
			<ChevronLeft class="h-4 w-4" />
		</Button>
		<div class="flex flex-col">
			<h1 class="text-xl font-semibold">Ticket Details</h1>
			<p class="text-xs text-muted-foreground">ID: {id}</p>
		</div>
	</header>

	<div class="flex-1 flex flex-col min-h-0">
		{#await dataPromise}
			<div class="p-6 space-y-4">
				<Skeleton class="h-20 w-3/4" />
				<Skeleton class="h-20 w-1/2 ml-auto" />
				<Skeleton class="h-20 w-3/4" />
			</div>
		{:then ticket}
			<div class="p-6 border-b bg-muted/30 shrink-0">
				<div class="flex items-center justify-between mb-2">
					<h2 class="text-2xl font-bold">{ticket.subject}</h2>
					<Badge
						class={`capitalize border ${statusColors[ticket.status!] || ''}`}
						variant="outline"
					>
						{ticket.status?.replace('_', ' ')}
					</Badge>
				</div>
				<p class="text-sm text-muted-foreground whitespace-pre-wrap">{ticket.description}</p>
			</div>

			<!-- Customer & All Info Accordion -->
			<Accordion.Root type="single" class="border-b bg-background shrink-0">
				<Accordion.Item value="info">
					<Accordion.Trigger class="px-6 py-3 hover:bg-muted/50 transition-colors">
						<div class="flex items-center gap-3">
							<User class="h-4 w-4 text-muted-foreground" />
							<div class="flex flex-col text-left">
								<span class="text-sm font-semibold">{ticket.customer?.name}</span>
								<span class="text-xs text-muted-foreground">{ticket.customer?.phone}</span>
							</div>
						</div>
					</Accordion.Trigger>
					<Accordion.Content class="px-6 pb-6 pt-2 bg-muted/5 space-y-6">
						<!-- Accordion Context: Split into columns -->
						<div class="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
							<!-- Customer Details -->
							<div class="space-y-3">
								<h4 class="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
									Customer
								</h4>
								<div class="space-y-1">
									<div class="flex justify-between text-sm">
										<span class="text-muted-foreground">Email:</span>
										<span class="font-medium truncate ml-2">{ticket.customer?.email || 'N/A'}</span>
									</div>
									<div class="flex justify-between text-sm">
										<span class="text-muted-foreground">Member Since:</span>
										<span class="font-medium">
											{ticket.customer?.createdAt
												? new Date(ticket.customer.createdAt).toLocaleDateString()
												: 'N/A'}
										</span>
									</div>
								</div>
							</div>

							<!-- Property & Room Info -->
							<div class="space-y-3">
								<h4 class="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
									Location
								</h4>
								<div class="space-y-2">
									<div class="flex items-center gap-2 text-sm">
										<Building class="h-3 w-3 text-muted-foreground" />
										<span class="font-medium">{ticket.property?.name || 'N/A'}</span>
									</div>
									<div class="flex items-center gap-2 text-sm">
										<HomeIcon class="h-3 w-3 text-muted-foreground" />
										<span class="font-medium">
											Room {ticket.room?.number || 'N/A'} ({ticket.room?.type || 'N/A'})
										</span>
									</div>
									<div class="text-xs text-muted-foreground pl-5 border-l-2 border-muted">
										{ticket.property?.city}, {ticket.property?.state}
									</div>
								</div>
							</div>

							<!-- Ticket Controls -->
							<div class="space-y-3">
								<h4 class="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
									Controls
								</h4>
								<div class="space-y-3">
									<div class="grid gap-1.5">
										<Label class="text-[10px]">Status</Label>
										<Select.Root
											type="single"
											value={ticket.status ?? undefined}
											onValueChange={updateStatus}
										>
											<Select.Trigger class="h-8 text-xs capitalize">
												{ticket.status?.replace('_', ' ')}
											</Select.Trigger>
											<Select.Content>
												<Select.Item value="open">Open</Select.Item>
												<Select.Item value="in_progress">In Progress</Select.Item>
												<Select.Item value="resolved">Resolved</Select.Item>
												<Select.Item value="closed">Closed</Select.Item>
											</Select.Content>
										</Select.Root>
									</div>
									<div class="grid gap-1.5">
										<Label class="text-[10px]">Priority</Label>
										<Select.Root
											type="single"
											value={ticket.priority ?? undefined}
											onValueChange={updatePriority}
										>
											<Select.Trigger class="h-8 text-xs capitalize">
												{ticket.priority}
											</Select.Trigger>
											<Select.Content>
												<Select.Item value="low">Low</Select.Item>
												<Select.Item value="medium">Medium</Select.Item>
												<Select.Item value="high">High</Select.Item>
											</Select.Content>
										</Select.Root>
									</div>
								</div>
							</div>

							<!-- Metadata -->
							<div class="space-y-3">
								<h4 class="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
									Metadata
								</h4>
								<div class="space-y-1.5 text-xs">
									<div class="flex justify-between">
										<span class="text-muted-foreground">Created:</span>
										<span class="font-medium">
											{ticket.createdAt ? new Date(ticket.createdAt).toLocaleDateString() : 'N/A'}
										</span>
									</div>
									<div class="flex justify-between">
										<span class="text-muted-foreground">Updated:</span>
										<span class="font-medium">
											{ticket.updatedAt ? new Date(ticket.updatedAt).toLocaleDateString() : 'N/A'}
										</span>
									</div>
									<div class="flex justify-between">
										<span class="text-muted-foreground">Total Messages:</span>
										<span class="font-medium">{ticket.messages?.length || 0}</span>
									</div>
									<div class="flex justify-between">
										<span class="text-muted-foreground">Issue Type:</span>
										<span class="font-medium capitalize">{ticket.type}</span>
									</div>
								</div>
							</div>
						</div>
					</Accordion.Content>
				</Accordion.Item>
			</Accordion.Root>

			<!-- Chat Area -->
			<ScrollArea class="flex-1 p-6 bg-background min-h-0">
				<div class="max-w-4xl mx-auto flex flex-col gap-6">
					<!-- Original Message (Description) -->
					<div class="flex gap-3">
						<div
							class="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-primary/10 text-primary"
						>
							<User class="h-4 w-4" />
						</div>
						<div class="flex flex-col gap-1 max-w-[80%]">
							<div class="flex items-center gap-2">
								<span class="text-sm font-semibold">{ticket.customer?.name}</span>
								<span class="text-[10px] text-muted-foreground">Original Ticket</span>
							</div>
							<div class="rounded-2xl rounded-tl-none bg-muted p-3 text-sm leading-relaxed">
								{ticket.description}
							</div>
						</div>
					</div>

					{#each ticket.messages as msg}
						{@const isMe = msg.senderId === ticket.assignedStaff?.id}
						<div class={`flex gap-3 ${isMe ? 'flex-row-reverse' : ''}`}>
							<div
								class={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full ${isMe ? 'bg-primary text-primary-foreground shadow-sm' : 'bg-muted text-muted-foreground'}`}
							>
								{#if isMe}
									<UserCheck class="h-4 w-4" />
								{:else}
									<User class="h-4 w-4" />
								{/if}
							</div>
							<div class={`flex flex-col gap-1 max-w-[80%] ${isMe ? 'items-end' : ''}`}>
								<div class="flex items-center gap-2 px-1">
									<span class="text-sm font-semibold">{msg.sender?.name}</span>
									<span class="text-[10px] text-muted-foreground">
										{msg.createdAt
											? new Date(msg.createdAt).toLocaleTimeString([], {
													hour: '2-digit',
													minute: '2-digit'
												})
											: ''}
									</span>
								</div>
								<div
									class={`rounded-2xl p-3 text-sm leading-relaxed shadow-sm ${isMe ? 'bg-primary text-primary-foreground rounded-tr-none' : 'bg-muted rounded-tl-none'}`}
								>
									{msg.content}
								</div>
							</div>
						</div>
					{/each}
				</div>
			</ScrollArea>

			<footer class="p-4 border-t bg-background shrink-0">
				<div class="max-w-4xl mx-auto">
					<form
						class="flex items-end gap-2"
						onsubmit={(e) => {
							e.preventDefault();
							handleSendMessage();
						}}
					>
						<div class="flex-1">
							<textarea
								name="message"
								rows="1"
								bind:value={messageContent}
								placeholder="Type your response..."
								class="flex w-full rounded-lg border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 resize-none transition-all"
								onkeydown={(e) => {
									if (e.key === 'Enter' && !e.shiftKey) {
										e.preventDefault();
										handleSendMessage();
									}
								}}
							></textarea>
						</div>
						<Button
							type="submit"
							size="icon"
							class="h-10 w-10 shrink-0 rounded-full shadow-lg transition-transform active:scale-95"
							disabled={!messageContent.trim()}
						>
							<Send class="h-4 w-4" />
						</Button>
					</form>
				</div>
			</footer>
		{/await}
	</div>
</div>

// src/app/(staff)/staff/tickets/[id]/page.tsx
'use client'

import { useState, useEffect, useCallback } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { use } from 'react'

interface StaffUser {
  id: string
  name: string
  role: string
}

interface StaffMember {
  id: string
  name: string
  email: string
  role: string
}

interface ConversationEntry {
  message: string
  timestamp: string
  sender: {
    relationTo: 'users' | 'customers'
    value: { id: string; name: string; role?: string }
  }
}

interface ProgressEntry {
  status: 'open' | 'in_progress' | 'resolved' | 'closed'
  updatedBy: {
    relationTo: 'users' | 'customers'
    value: { id: string; name: string; role?: string }
  }
  note?: string
  updatedAt: string
}

interface SupportTicket {
  id: string
  type: string
  description: string
  status: 'open' | 'in_progress' | 'resolved' | 'closed'
  createdAt: string
  staff?: { id: string; name: string; role: string }
  customer: { id: string; name: string }
  conversation: ConversationEntry[]
  progress?: ProgressEntry[]
  property?: { id: string; name: string }
}

export default function StaffTicketDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params)
  const router = useRouter()
  const [user, setUser] = useState<StaffUser | null>(null)
  const [ticket, setTicket] = useState<SupportTicket | null>(null)
  const [loading, setLoading] = useState(true)
  const [message, setMessage] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [showReassignDialog, setShowReassignDialog] = useState(false)
  const [staffList, setStaffList] = useState<StaffMember[]>([])
  const [selectedStaffId, setSelectedStaffId] = useState<string>('')
  const [reassignNote, setReassignNote] = useState('')
  const [showProgressTimeline, setShowProgressTimeline] = useState(false)

  const fetchTicket = useCallback(async () => {
    try {
      const userRes = await fetch('/api/custom/staff/me')
      if (!userRes.ok) {
        router.push('/staff/login')
        return
      }
      const userData = await userRes.json()
      setUser(userData.user)

      const ticketRes = await fetch(`/api/custom/staff/support/tickets/${id}`)
      if (ticketRes.ok) {
        const ticketData = await ticketRes.json()
        setTicket(ticketData.ticket)
      }
    } catch (error) {
      console.error('Failed to fetch ticket:', error)
    } finally {
      setLoading(false)
    }
  }, [id, router])

  useEffect(() => {
    fetchTicket()
  }, [fetchTicket])

  // Fetch staff list for managers/admins
  const fetchStaffList = useCallback(async () => {
    if (!user || (user.role !== 'manager' && user.role !== 'admin')) return

    try {
      const res = await fetch('/api/custom/staff/users')
      if (res.ok) {
        const data = await res.json()
        setStaffList(data.staff || [])
      }
    } catch (error) {
      console.error('Failed to fetch staff list:', error)
    }
  }, [user])

  useEffect(() => {
    if (user && (user.role === 'manager' || user.role === 'admin')) {
      fetchStaffList()
    }
  }, [user, fetchStaffList])

  const handleAssign = async (action: 'claim' | 'unassign') => {
    if (!user) return
    setSubmitting(true)
    try {
      const res = await fetch(`/api/custom/staff/support/tickets/${id}/assign`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action }),
      })
      if (res.ok) {
        await fetchTicket()
      }
    } catch (error) {
      console.error('Failed to assign ticket:', error)
    } finally {
      setSubmitting(false)
    }
  }

  const handleSendMessage = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!message.trim()) return

    setSubmitting(true)
    try {
      const res = await fetch(`/api/custom/staff/support/tickets/${id}/message`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ message: message.trim() }),
      })
      if (res.ok) {
        setMessage('')
        await fetchTicket()
      }
    } catch (error) {
      console.error('Failed to send message:', error)
    } finally {
      setSubmitting(false)
    }
  }

  const handleReassign = async () => {
    if (!user || (user.role !== 'manager' && user.role !== 'admin')) return

    setSubmitting(true)
    try {
      const res = await fetch(`/api/custom/staff/support/tickets/${id}/reassign`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          staffId: selectedStaffId || null,
          note: reassignNote || undefined,
        }),
      })
      if (res.ok) {
        setShowReassignDialog(false)
        setSelectedStaffId('')
        setReassignNote('')
        await fetchTicket()
      }
    } catch (error) {
      console.error('Failed to reassign ticket:', error)
    } finally {
      setSubmitting(false)
    }
  }

  const statusBadgeClass = {
    open: 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/20 dark:text-yellow-400',
    in_progress: 'bg-blue-100 text-blue-800 dark:bg-blue-900/20 dark:text-blue-400',
    resolved: 'bg-green-100 text-green-800 dark:bg-green-900/20 dark:text-green-400',
    closed: 'bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-300',
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 dark:bg-gray-900 flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
      </div>
    )
  }

  if (!ticket) {
    return (
      <div className="min-h-screen bg-gray-50 dark:bg-gray-900 flex items-center justify-center">
        <div className="text-center">
          <p className="text-gray-600 dark:text-gray-400 mb-4">Ticket not found</p>
          <Link href="/staff/tickets" className="text-blue-600 dark:text-blue-400 hover:underline">
            Back to Tickets
          </Link>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      <header className="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 sticky top-0 z-10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center py-4">
            <div className="flex items-center space-x-4">
              <Link
                href="/staff/tickets"
                className="text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white"
              >
                ← Back
              </Link>
              <h1 className="text-xl font-bold text-gray-900 dark:text-white">Ticket Details</h1>
            </div>
            <div className="flex items-center space-x-2">
              {user?.role === 'manager' || user?.role === 'admin' ? (
                <button
                  onClick={() => setShowReassignDialog(true)}
                  disabled={submitting}
                  className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:opacity-50 text-sm"
                >
                  Reassign
                </button>
              ) : null}
              {!ticket.staff ? (
                <button
                  onClick={() => handleAssign('claim')}
                  disabled={submitting}
                  className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 text-sm"
                >
                  Claim Ticket
                </button>
              ) : ticket.staff.id === user?.id ? (
                <button
                  onClick={() => handleAssign('unassign')}
                  disabled={submitting}
                  className="px-4 py-2 bg-gray-200 text-gray-800 dark:bg-gray-700 dark:text-gray-200 rounded-lg hover:bg-gray-300 dark:hover:bg-gray-600 disabled:opacity-50 text-sm"
                >
                  Unassign
                </button>
              ) : null}
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <div className="lg:col-span-1">
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm p-6 space-y-4">
              <div>
                <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">Status</p>
                <span
                  className={`inline-block px-3 py-1 text-sm font-medium rounded ${
                    statusBadgeClass[ticket.status]
                  }`}
                >
                  {ticket.status.replace('_', ' ').toUpperCase()}
                </span>
              </div>
              <div>
                <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">Type</p>
                <p className="text-gray-900 dark:text-white capitalize">{ticket.type}</p>
              </div>
              <div>
                <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">Customer</p>
                <p className="text-gray-900 dark:text-white">{ticket.customer.name}</p>
              </div>
              {ticket.property && (
                <div>
                  <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">Property</p>
                  <p className="text-gray-900 dark:text-white">{ticket.property.name}</p>
                </div>
              )}
              <div>
                <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">Assigned To</p>
                <p className="text-gray-900 dark:text-white">
                  {ticket.staff ? ticket.staff.name : 'Unassigned'}
                </p>
              </div>
              <div>
                <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">Created</p>
                <p className="text-gray-900 dark:text-white text-sm">
                  {new Date(ticket.createdAt).toLocaleString()}
                </p>
              </div>

              {/* Progress History Section */}
              {(user?.role === 'manager' || user?.role === 'admin') &&
                ticket.progress &&
                ticket.progress.length > 0 && (
                  <div className="pt-4 border-t border-gray-200 dark:border-gray-700">
                    <button
                      onClick={() => setShowProgressTimeline(!showProgressTimeline)}
                      className="flex items-center justify-between w-full text-sm font-medium text-gray-700 dark:text-gray-300 hover:text-gray-900 dark:hover:text-white"
                    >
                      <span>Progress History ({ticket.progress.length})</span>
                      <span className="text-xs">{showProgressTimeline ? '▼' : '▶'}</span>
                    </button>

                    {showProgressTimeline && (
                      <div className="mt-3 space-y-3 max-h-60 overflow-y-auto">
                        {ticket.progress
                          .slice()
                          .reverse()
                          .map((entry, idx) => {
                            const updatedByData =
                              typeof entry.updatedBy === 'object' && 'value' in entry.updatedBy
                                ? entry.updatedBy.value
                                : null
                            const updatedByName =
                              typeof updatedByData === 'object' &&
                              updatedByData &&
                              'name' in updatedByData
                                ? updatedByData.name
                                : 'Unknown'
                            const updatedByRole =
                              typeof updatedByData === 'object' &&
                              updatedByData &&
                              'role' in updatedByData
                                ? updatedByData.role
                                : 'user'

                            return (
                              <div
                                key={idx}
                                className="relative pl-6 pb-3 border-l-2 border-gray-300 dark:border-gray-600 last:border-l-0 last:pb-0"
                              >
                                <div className="absolute left-0 top-0 -ml-1.5 w-3 h-3 rounded-full bg-blue-500 dark:bg-blue-400"></div>
                                <div className="text-xs text-gray-500 dark:text-gray-400">
                                  {new Date(entry.updatedAt).toLocaleString()}
                                </div>
                                <div className="text-sm font-medium text-gray-900 dark:text-white mt-1">
                                  Status: {entry.status.replace('_', ' ').toUpperCase()}
                                </div>
                                <div className="text-xs text-gray-600 dark:text-gray-400 mt-1">
                                  By: {updatedByName}{' '}
                                  <span className="text-gray-500">({updatedByRole})</span>
                                </div>
                                {entry.note && (
                                  <div className="text-xs text-gray-700 dark:text-gray-300 mt-1 bg-gray-50 dark:bg-gray-700/50 p-2 rounded">
                                    {entry.note}
                                  </div>
                                )}
                              </div>
                            )
                          })}
                      </div>
                    )}
                  </div>
                )}
            </div>
          </div>

          <div className="lg:col-span-2">
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm">
              <div className="p-6 border-b border-gray-200 dark:border-gray-700">
                <h2 className="text-lg font-semibold text-gray-900 dark:text-white">
                  {ticket.description}
                </h2>
              </div>

              <div className="p-6 space-y-4 max-h-[500px] overflow-y-auto">
                {ticket.conversation.map((entry, idx) => {
                  const isStaff = entry.sender.relationTo === 'users'
                  const isCurrentUser = isStaff && entry.sender.value.id === user?.id

                  return (
                    <div
                      key={idx}
                      className={`flex ${isCurrentUser ? 'justify-end' : 'justify-start'}`}
                    >
                      <div
                        className={`max-w-[80%] rounded-lg p-4 ${
                          isCurrentUser
                            ? 'bg-blue-600 text-white'
                            : isStaff
                              ? 'bg-purple-100 dark:bg-purple-900/20'
                              : 'bg-gray-100 dark:bg-gray-700'
                        }`}
                      >
                        <div className="flex items-center space-x-2 mb-1">
                          <span
                            className={`text-sm font-medium ${
                              isCurrentUser ? 'text-blue-100' : 'text-gray-900 dark:text-white'
                            }`}
                          >
                            {entry.sender.value.name}
                          </span>
                          {isStaff && (
                            <span
                              className={`text-xs px-2 py-0.5 rounded ${
                                isCurrentUser
                                  ? 'bg-blue-500 text-white'
                                  : 'bg-purple-200 text-purple-800 dark:bg-purple-800 dark:text-purple-200'
                              }`}
                            >
                              Staff
                            </span>
                          )}
                        </div>
                        <p
                          className={`text-sm ${
                            isCurrentUser ? 'text-white' : 'text-gray-800 dark:text-gray-200'
                          }`}
                        >
                          {entry.message}
                        </p>
                        <p
                          className={`text-xs mt-1 ${
                            isCurrentUser ? 'text-blue-200' : 'text-gray-500 dark:text-gray-400'
                          }`}
                        >
                          {new Date(entry.timestamp).toLocaleString()}
                        </p>
                      </div>
                    </div>
                  )
                })}
              </div>

              <div className="p-6 border-t border-gray-200 dark:border-gray-700">
                <form onSubmit={handleSendMessage}>
                  <div className="flex space-x-3">
                    <input
                      type="text"
                      value={message}
                      onChange={(e) => setMessage(e.target.value)}
                      placeholder="Type your reply..."
                      className="flex-1 rounded-lg border border-gray-300 dark:border-gray-600 px-4 py-2 bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                      disabled={submitting}
                    />
                    <button
                      type="submit"
                      disabled={submitting || !message.trim()}
                      className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      Send
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </main>

      {/* Reassignment Dialog */}
      {showReassignDialog && (user?.role === 'manager' || user?.role === 'admin') && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow-xl max-w-md w-full p-6">
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
              Reassign Ticket
            </h3>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Assign To
                </label>
                <select
                  value={selectedStaffId}
                  onChange={(e) => setSelectedStaffId(e.target.value)}
                  className="w-full rounded-lg border border-gray-300 dark:border-gray-600 px-4 py-2 bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                >
                  <option value="">Unassign (No staff)</option>
                  {staffList.map((staff) => (
                    <option key={staff.id} value={staff.id}>
                      {staff.name} ({staff.role})
                    </option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Note (Optional)
                </label>
                <textarea
                  value={reassignNote}
                  onChange={(e) => setReassignNote(e.target.value)}
                  placeholder="Add a note about this reassignment..."
                  rows={3}
                  className="w-full rounded-lg border border-gray-300 dark:border-gray-600 px-4 py-2 bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                />
              </div>
              <div className="flex justify-end space-x-3 pt-2">
                <button
                  onClick={() => {
                    setShowReassignDialog(false)
                    setSelectedStaffId('')
                    setReassignNote('')
                  }}
                  disabled={submitting}
                  className="px-4 py-2 bg-gray-200 text-gray-800 dark:bg-gray-700 dark:text-gray-200 rounded-lg hover:bg-gray-300 dark:hover:bg-gray-600 disabled:opacity-50"
                >
                  Cancel
                </button>
                <button
                  onClick={handleReassign}
                  disabled={submitting}
                  className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:opacity-50"
                >
                  {submitting ? 'Reassigning...' : 'Reassign'}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
