// src/routes/dashboard/+page.svelte
<script lang="ts">
	import {
		Card,
		CardContent,
		CardHeader,
		CardTitle,
		CardDescription,
		CardFooter
	} from '$lib/components/ui/card';
	import { Button } from '$lib/components/ui/button';
	import { Badge } from '$lib/components/ui/badge';
	import * as Table from '$lib/components/ui/table';

	let { data } = $props();
</script>

<div class="space-y-6">
	<div>
		<h1 class="text-3xl font-bold tracking-tight">Welcome back, {data.user.name.split(' ')[0]}!</h1>
		<p class="text-muted-foreground">Here is an overview of your account.</p>
	</div>

	{#if !data.customer}
		<Card>
			<CardHeader>
				<CardTitle>Profile Setup Required</CardTitle>
				<CardDescription>We couldn't find a tenant profile linked to your account.</CardDescription>
			</CardHeader>
			<CardContent>
				<p>Please contact support or waiting for admin approval.</p>
			</CardContent>
		</Card>
	{:else}
		<!-- Active Booking / Room Info -->
		<div class="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
			<Card>
				<CardHeader>
					<CardTitle>Current Stay</CardTitle>
					<CardDescription>Your active room details.</CardDescription>
				</CardHeader>
				<CardContent>
					{#if data.customer.bookings.length > 0}
						{@const booking = data.customer.bookings[0]}
						<div class="text-2xl font-bold">{booking.property?.name}</div>
						<div class="text-muted-foreground">Room {booking.room?.number}</div>
						<div class="mt-4 text-sm">
							<div class="flex justify-between">
								<span>Rent:</span>
								<span class="font-medium">${booking.rentAmount}/mo</span>
							</div>
							<div class="flex justify-between">
								<span>Move-in:</span>
								<span>{new Date(booking.startDate).toLocaleDateString()}</span>
							</div>
						</div>
					{:else}
						<p class="text-muted-foreground">No active bookings found.</p>
					{/if}
				</CardContent>
			</Card>

			<Card>
				<CardHeader>
					<CardTitle>Account Status</CardTitle>
					<CardDescription>Your profile status.</CardDescription>
				</CardHeader>
				<CardContent>
					<div class="flex flex-col gap-2">
						<div class="flex justify-between items-center">
							<span class="text-muted-foreground">Profile:</span>
							<Badge variant={data.customer.status === 'active' ? 'default' : 'secondary'}
								>{data.customer.status?.toUpperCase()}</Badge
							>
						</div>
						<div class="flex justify-between items-center">
							<span class="text-muted-foreground">Email:</span>
							<span>{data.customer.email}</span>
						</div>
					</div>
				</CardContent>
				<CardFooter>
					<!-- Trigger edit profile if needed or support -->
					<Button variant="outline" size="sm">Contact Support</Button>
				</CardFooter>
			</Card>

			<Card>
				<CardHeader>
					<CardTitle>Quick Actions</CardTitle>
				</CardHeader>
				<CardContent class="grid gap-2">
					<Button href="/dashboard/tickets/create" variant="secondary">Raise a Ticket</Button>
					<Button href="/dashboard/payments" variant="outline">View Payments</Button>
				</CardContent>
			</Card>
		</div>

		<!-- Recent Payments -->
		<Card>
			<CardHeader>
				<CardTitle>Recent Payments</CardTitle>
				<CardDescription>Your last 5 transactions.</CardDescription>
			</CardHeader>
			<CardContent>
				<Table.Root>
					<Table.Header>
						<Table.Row>
							<Table.Head>Date</Table.Head>
							<Table.Head>Type</Table.Head>
							<Table.Head>Amount</Table.Head>
							<Table.Head>Status</Table.Head>
						</Table.Row>
					</Table.Header>
					<Table.Body>
						{#each data.customer.payments as payment}
							<Table.Row>
								<Table.Cell
									>{payment?.paymentDate
										? new Date(payment.paymentDate).toLocaleDateString()
										: ''}</Table.Cell
								>
								<Table.Cell class="capitalize">{payment.type.replace('_', ' ')}</Table.Cell>
								<Table.Cell>${payment.amount}</Table.Cell>
								<Table.Cell>
									<Badge variant={payment.status === 'paid' ? 'default' : 'secondary'}
										>{payment.status}</Badge
									>
								</Table.Cell>
							</Table.Row>
						{:else}
							<Table.Row>
								<Table.Cell colspan={4} class="text-center text-muted-foreground"
									>No recent payments.</Table.Cell
								>
							</Table.Row>
						{/each}
					</Table.Body>
				</Table.Root>
			</CardContent>
		</Card>
	{/if}
</div>

// src/app/(frontend)/dashboard/page.tsx
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Calendar, CheckCircle, CreditCard, Home, TrendingUp, User } from 'lucide-react'
import Link from 'next/link'

export default function DashboardPage() {
  return (
    <div className="space-y-6">
      {/* Page header */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight sm:text-3xl">Dashboard</h1>
          <p className="text-muted-foreground">
            Welcome back! Here&apos;s what&apos;s happening with your account.
          </p>
        </div>
        <div className="flex items-center space-x-2">
          <Button asChild>
            <Link href="/dashboard/bookings">
              <Calendar className="mr-2 h-4 w-4" />
              View Bookings
            </Link>
          </Button>
        </div>
      </div>

      {/* Overview cards */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <Card className="p-4 sm:p-6">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2 px-0 pt-0">
            <CardTitle className="text-sm font-medium">Active Bookings</CardTitle>
            <Home className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent className="px-0 pb-0">
            <div className="text-2xl font-bold">2</div>
            <p className="text-xs text-muted-foreground">+1 from last month</p>
          </CardContent>
        </Card>

        <Card className="p-4 sm:p-6">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2 px-0 pt-0">
            <CardTitle className="text-sm font-medium">Monthly Rent</CardTitle>
            <CreditCard className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent className="px-0 pb-0">
            <div className="text-2xl font-bold">₹15,000</div>
            <p className="text-xs text-muted-foreground">Due in 5 days</p>
          </CardContent>
        </Card>

        <Card className="p-4 sm:p-6">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2 px-0 pt-0">
            <CardTitle className="text-sm font-medium">Payment Status</CardTitle>
            <CheckCircle className="h-4 w-4 text-green-600" />
          </CardHeader>
          <CardContent className="px-0 pb-0">
            <div className="text-2xl font-bold">Up to date</div>
            <p className="text-xs text-muted-foreground">No pending payments</p>
          </CardContent>
        </Card>

        <Card className="p-4 sm:p-6">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2 px-0 pt-0">
            <CardTitle className="text-sm font-medium">Total Spent</CardTitle>
            <TrendingUp className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent className="px-0 pb-0">
            <div className="text-2xl font-bold">₹45,000</div>
            <p className="text-xs text-muted-foreground">This year</p>
          </CardContent>
        </Card>
      </div>

      {/* Quick actions and alerts */}
      <div className="grid gap-6 lg:grid-cols-3">
        {/* Quick actions */}
        <Card className="lg:col-span-2">
          <CardHeader>
            <CardTitle>Quick Actions</CardTitle>
            <CardDescription>Common tasks and shortcuts</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <Button variant="outline" className="h-20 flex-col" asChild>
                <Link href="/dashboard/profile">
                  <User className="mb-2 h-6 w-6" />
                  Update Profile
                </Link>
              </Button>
              <Button variant="outline" className="h-20 flex-col" asChild>
                <Link href="/dashboard/rent">
                  <CreditCard className="mb-2 h-6 w-6" />
                  Pay Rent
                </Link>
              </Button>
              <Button variant="outline" className="h-20 flex-col" asChild>
                <Link href="/dashboard/bookings">
                  <Calendar className="mb-2 h-6 w-6" />
                  View Bookings
                </Link>
              </Button>
              <Button variant="outline" className="h-20 flex-col" asChild>
                <Link href="/dashboard/settings">
                  <User className="mb-2 h-6 w-6" />
                  Settings
                </Link>
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* Recent activity */}
        <Card>
          <CardHeader>
            <CardTitle>Recent Activity</CardTitle>
            <CardDescription>Your latest transactions and updates</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div className="flex items-center space-x-4">
                <div className="h-2 w-2 rounded-full bg-green-600"></div>
                <div className="flex-1 space-y-1">
                  <p className="text-sm font-medium">Rent payment completed</p>
                  <p className="text-xs text-muted-foreground">2 days ago</p>
                </div>
                <Badge variant="secondary">₹15,000</Badge>
              </div>

              <div className="flex items-center space-x-4">
                <div className="h-2 w-2 rounded-full bg-blue-600"></div>
                <div className="flex-1 space-y-1">
                  <p className="text-sm font-medium">Booking extended</p>
                  <p className="text-xs text-muted-foreground">1 week ago</p>
                </div>
                <Badge variant="outline">Extended</Badge>
              </div>

              <div className="flex items-center space-x-4">
                <div className="h-2 w-2 rounded-full bg-yellow-600"></div>
                <div className="flex-1 space-y-1">
                  <p className="text-sm font-medium">Maintenance request</p>
                  <p className="text-xs text-muted-foreground">2 weeks ago</p>
                </div>
                <Badge variant="outline">Pending</Badge>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Upcoming payments */}
      <Card>
        <CardHeader>
          <CardTitle>Upcoming Payments</CardTitle>
          <CardDescription>Your scheduled payments and due dates</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            <div className="flex flex-col gap-4 p-4 border rounded-lg sm:flex-row sm:items-center sm:justify-between">
              <div className="flex items-center space-x-4">
                <div className="h-10 w-10 rounded-full bg-primary/10 flex items-center justify-center">
                  <CreditCard className="h-5 w-5 text-primary" />
                </div>
                <div>
                  <p className="font-medium">Monthly Rent</p>
                  <p className="text-sm text-muted-foreground">Room 101, FLY Colive</p>
                </div>
              </div>
              <div className="flex flex-col items-start gap-2 sm:items-end sm:gap-0">
                <div className="text-right">
                  <p className="font-medium">₹15,000</p>
                  <p className="text-sm text-muted-foreground">Due in 5 days</p>
                </div>
                <Button size="sm">Pay Now</Button>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
