// src/app/(frontend)/dashboard/bookings/page.tsx
'use client'

import React, { useState, useEffect } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { BookingCard } from '@/components/dashboard/BookingCard'
import { Calendar, Filter, Search, RefreshCw, AlertCircle } from 'lucide-react'
import Link from 'next/link'
import { useBookings, usePrefetchBookings } from '@/hooks/useBookings'

export default function BookingsPage() {
  const [page, setPage] = useState(1)
  const [filters, setFilters] = useState({
    status: 'all',
    sortBy: 'createdAt',
    sortOrder: 'desc',
    search: '',
  })

  // Use React Query hook
  const { data, isLoading, error, refetch } = useBookings({
    page,
    limit: 10,
    ...filters,
  })

  const { prefetchPage } = usePrefetchBookings()

  // Prefetch next page when user is on current page
  useEffect(() => {
    if (data?.pagination?.hasNextPage) {
      prefetchPage({
        page: page + 1,
        limit: 10,
        ...filters,
      })
    }
  }, [data, page, filters, prefetchPage])

  const bookings = data?.bookings || []
  const pagination = data?.pagination || {
    page: 1,
    limit: 10,
    totalPages: 1,
    totalDocs: 0,
    hasNextPage: false,
    hasPrevPage: false,
  }
  const stats = data?.stats || {
    total: 0,
    active: 0,
    pending: 0,
  }

  const handleFilterChange = (key: string, value: string) => {
    setFilters((prev) => ({ ...prev, [key]: value }))
    setPage(1) // Reset to first page
  }

  const handlePageChange = (newPage: number) => {
    setPage(newPage)
  }

  const handleRefresh = () => {
    refetch()
  }

  return (
    <div className="space-y-6">
      {/* Page header */}
      <div className="flex flex-col md:flex-row gap-4 md:gap-0 items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">My Bookings</h1>
          <p className="text-muted-foreground">Manage and track all your property bookings</p>
        </div>
        <div className="flex items-center justify-end md:justify-start w-full md:w-auto space-x-2">
          <Button onClick={handleRefresh} variant="outline" size="lg">
            <RefreshCw className="mr-2 h-4 w-4" />
            Refresh
          </Button>
          <Button variant="outline" size="lg" asChild>
            <Link href="/dashboard/bookings/history">
              <Calendar className="mr-2 h-4 w-4" />
              View History
            </Link>
          </Button>
        </div>
      </div>

      {/* Stats cards */}
      <div className="grid gap-4 md:grid-cols-3">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Bookings</CardTitle>
            <Calendar className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{stats.total}</div>
            <p className="text-xs text-muted-foreground">All time bookings</p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Active Bookings</CardTitle>
            <Badge variant="default" className="h-4 w-4" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{stats.active}</div>
            <p className="text-xs text-muted-foreground">Currently active</p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Pending Bookings</CardTitle>
            <Badge variant="secondary" className="h-4 w-4" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{stats.pending}</div>
            <p className="text-xs text-muted-foreground">Awaiting confirmation</p>
          </CardContent>
        </Card>
      </div>

      {/* Filters */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center">
            <Filter className="mr-2 h-5 w-5" />
            Filters & Search
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid gap-4 grid-cols-2 md:grid-cols-4">
            <div className="space-y-2">
              <label className="text-sm font-medium">Status</label>
              <Select
                value={filters.status}
                onValueChange={(value) => handleFilterChange('status', value)}
              >
                <SelectTrigger>
                  <SelectValue placeholder="All statuses" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Statuses</SelectItem>
                  <SelectItem value="pending">Pending</SelectItem>
                  <SelectItem value="confirmed">Confirmed</SelectItem>
                  <SelectItem value="completed">Completed</SelectItem>
                  <SelectItem value="cancelled">Cancelled</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <label className="text-sm font-medium">Sort By</label>
              <Select
                value={filters.sortBy}
                onValueChange={(value) => handleFilterChange('sortBy', value)}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Sort by" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="createdAt">Booking Date</SelectItem>
                  <SelectItem value="total">Total Amount</SelectItem>
                  <SelectItem value="status">Status</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <label className="text-sm font-medium">Order</label>
              <Select
                value={filters.sortOrder}
                onValueChange={(value) => handleFilterChange('sortOrder', value)}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Order" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="desc">Newest First</SelectItem>
                  <SelectItem value="asc">Oldest First</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2 col-span-2 md:col-span-full">
              <label className="text-sm font-medium">Search</label>
              <div className="relative">
                <Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
                <Input
                  placeholder="Search properties..."
                  value={filters.search}
                  onChange={(e) => handleFilterChange('search', e.target.value)}
                  className="pl-10"
                />
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Bookings list */}
      <div className="space-y-4">
        {error ? (
          <Card>
            <CardContent className="flex flex-col items-center justify-center py-12">
              <AlertCircle className="h-12 w-12 text-red-600 mb-4" />
              <h3 className="text-lg font-semibold mb-2">Failed to Load Bookings</h3>
              <p className="text-muted-foreground text-center mb-4">
                {error instanceof Error ? error.message : 'Failed to load bookings'}
              </p>
              <Button onClick={handleRefresh}>
                <RefreshCw className="mr-2 h-4 w-4" />
                Try Again
              </Button>
            </CardContent>
          </Card>
        ) : isLoading ? (
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {[...Array(6)].map((_, i) => (
              <Card key={i} className="animate-pulse">
                <CardHeader>
                  <div className="h-4 bg-muted rounded w-3/4"></div>
                  <div className="h-3 bg-muted rounded w-1/2"></div>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    <div className="h-4 bg-muted rounded"></div>
                    <div className="h-4 bg-muted rounded w-2/3"></div>
                    <div className="h-4 bg-muted rounded w-1/2"></div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        ) : bookings.length === 0 ? (
          <Card>
            <CardContent className="flex flex-col items-center justify-center py-12">
              <Calendar className="h-12 w-12 text-muted-foreground mb-4" />
              <h3 className="text-lg font-semibold mb-2">No bookings found</h3>
              <p className="text-muted-foreground text-center mb-4">
                {filters.status !== 'all' || filters.search
                  ? 'Try adjusting your filters to see more results.'
                  : "You haven't made any bookings yet."}
              </p>
              <Button asChild>
                <Link href="/properties">Browse Properties</Link>
              </Button>
            </CardContent>
          </Card>
        ) : (
          <>
            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
              {bookings.map((booking) => (
                <BookingCard key={booking.id} booking={booking} />
              ))}
            </div>

            {/* Pagination */}
            {pagination.totalPages > 1 && (
              <div className="flex items-center justify-between">
                <p className="text-sm text-muted-foreground">
                  Showing {(pagination.page - 1) * pagination.limit + 1} to{' '}
                  {Math.min(pagination.page * pagination.limit, pagination.totalDocs)} of{' '}
                  {pagination.totalDocs} bookings
                </p>
                <div className="flex items-center space-x-2">
                  <Button
                    variant="outline"
                    size="lg"
                    onClick={() => handlePageChange(pagination.page - 1)}
                    disabled={!pagination.hasPrevPage}
                  >
                    Previous
                  </Button>
                  <span className="text-sm">
                    Page {pagination.page} of {pagination.totalPages}
                  </span>
                  <Button
                    variant="outline"
                    size="lg"
                    onClick={() => handlePageChange(pagination.page + 1)}
                    disabled={!pagination.hasNextPage}
                  >
                    Next
                  </Button>
                </div>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  )
}

// src/routes/admin/bookings/+page.svelte
<script lang="ts">
	import { Badge } from '$lib/components/ui/badge';
	import { Button } from '$lib/components/ui/button';
	import { Calendar } from '$lib/components/ui/calendar';
	import * as Card from '$lib/components/ui/card';
	import * as InputGroup from '$lib/components/ui/input-group';
	import * as Pagination from '$lib/components/ui/pagination';
	import * as Popover from '$lib/components/ui/popover';
	import * as Select from '$lib/components/ui/select';
	import { Skeleton } from '$lib/components/ui/skeleton';
	import * as Table from '$lib/components/ui/table';
	import { type DateValue } from '@internationalized/date';
	import { ArrowBigRight, Calendar as CalendarIcon, Loader, Plus, Search, X } from 'lucide-svelte';
	import { Debounced } from 'runed';
	import { getCustomers } from '../customers/customers.remote';
	import { getProperties } from '../properties/properties.remote';
	import BookingForm from './_components/booking-form.svelte';
	import { getBookings } from './bookings.remote';

	let searchTerm = $state('');
	let dateFrom = $state<DateValue | undefined>(undefined);
	let dateTo = $state<DateValue | undefined>(undefined);
	let currentPage = $state(1);
	let pageSize = $state(10);
	let bookingSheetOpen = $state(false);
	let datePopoverOpen = $state(false);
	let dateToPopoverOpen = $state(false);

	const debouncedSearchTerm = new Debounced(() => searchTerm, 500);

	let bookingsPromise = $derived(
		getBookings({
			searchTerm: debouncedSearchTerm.current,
			dateFrom: dateFrom?.toString(),
			dateTo: dateTo?.toString(),
			page: currentPage,
			pageSize: pageSize
		})
	);

	let dependenciesPromise = $derived(Promise.all([getProperties({}), getCustomers({})]));

	function clearDateFilter() {
		dateFrom = undefined;
		dateTo = undefined;
	}
</script>

<div class="flex items-center justify-between space-y-2 p-6">
	<h2 class="text-3xl font-bold tracking-tight">Bookings</h2>
	<div class="flex items-center space-x-2">
		<Button onclick={() => (bookingSheetOpen = true)}>
			<Plus class="mr-2 h-4 w-4" /> Add Booking
		</Button>
	</div>
</div>

<div class="p-6 pt-0 space-y-4">
	<div class="flex items-center gap-2 flex-wrap">
		<InputGroup.Root class="max-w-sm">
			<InputGroup.Input placeholder="Search..." bind:value={searchTerm} />
			<InputGroup.Button>
				<Search class="h-4 w-4" />
			</InputGroup.Button>
		</InputGroup.Root>

		<Popover.Root bind:open={datePopoverOpen}>
			<Popover.Trigger>
				{#snippet child({ props })}
					<Button variant="outline" class="justify-start text-left font-normal" {...props}>
						<CalendarIcon class="mr-2 h-4 w-4" />
						{#if dateFrom}
							From: {dateFrom.toString()}
						{:else}
							Start Date
						{/if}
					</Button>
				{/snippet}
			</Popover.Trigger>
			<Popover.Content class="w-auto p-0" align="start">
				<Calendar type="single" bind:value={dateFrom} placeholder={dateFrom} />
				<div class="p-3 border-t flex justify-end">
					<Button size="sm" onclick={() => (datePopoverOpen = false)}>Done</Button>
				</div>
			</Popover.Content>
		</Popover.Root>

		<Popover.Root bind:open={dateToPopoverOpen}>
			<Popover.Trigger>
				{#snippet child({ props })}
					<Button variant="outline" class="justify-start text-left font-normal" {...props}>
						<CalendarIcon class="mr-2 h-4 w-4" />
						{#if dateTo}
							To: {dateTo.toString()}
						{:else}
							End Date
						{/if}
					</Button>
				{/snippet}
			</Popover.Trigger>
			<Popover.Content class="w-auto p-0" align="start">
				<Calendar type="single" bind:value={dateTo} placeholder={dateTo} />
				<div class="p-3 border-t flex justify-end">
					<Button size="sm" onclick={() => (dateToPopoverOpen = false)}>Done</Button>
				</div>
			</Popover.Content>
		</Popover.Root>

		{#if dateFrom || dateTo}
			<Button variant="ghost" size="icon" onclick={clearDateFilter}>
				<X class="h-4 w-4" />
			</Button>
		{/if}
	</div>

	<svelte:boundary>
		{#await bookingsPromise}
			<div class="space-y-4">
				<Skeleton class="h-12 w-full" />
				<Skeleton class="h-12 w-full" />
				<Skeleton class="h-12 w-full" />
			</div>
		{:then data}
			<Card.Root>
				<Card.Content class="p-0">
					<Table.Root>
						<Table.Header>
							<Table.Row>
								<Table.Head>Property</Table.Head>
								<Table.Head>Room</Table.Head>
								<Table.Head>Customer</Table.Head>
								<Table.Head>Dates</Table.Head>
								<Table.Head>Status</Table.Head>
								<Table.Head class="text-right">Actions</Table.Head>
							</Table.Row>
						</Table.Header>
						<Table.Body>
							{#each data.bookings as booking}
								<Table.Row>
									<Table.Cell class="font-medium">
										{booking.property?.name || 'Unknown'}
									</Table.Cell>
									<Table.Cell>
										{booking.room?.number || booking.roomId}
									</Table.Cell>
									<Table.Cell>
										{booking.customer?.name || booking.customerId}
									</Table.Cell>
									<Table.Cell>
										{new Date(booking.startDate).toLocaleDateString()} -
										{booking.endDate ? new Date(booking.endDate).toLocaleDateString() : 'Ongoing'}
									</Table.Cell>
									<Table.Cell>
										<Badge variant={booking.status === 'active' ? 'default' : 'secondary'}>
											{booking.status}
										</Badge>
									</Table.Cell>
									<Table.Cell class="text-right">
										<Button variant="outline" size="icon" href="/admin/bookings/{booking.id}">
											<ArrowBigRight class="h-4 w-4" />
										</Button>
									</Table.Cell>
								</Table.Row>
							{:else}
								<Table.Row>
									<Table.Cell colspan={6} class="h-24 text-center">No bookings found.</Table.Cell>
								</Table.Row>
							{/each}
						</Table.Body>
					</Table.Root>
				</Card.Content>
			</Card.Root>

			{#if data.totalPages && data.totalPages > 1}
				<div class="flex flex-col p-4 gap-4">
					<div class="flex items-center justify-between gap-4">
						<p class="text-sm text-muted-foreground">
							Showing {(data.page - 1) * data.pageSize + 1} to {Math.min(
								data.page * data.pageSize,
								data.total
							)} of {data.total} bookings
						</p>
						<Select.Root
							type="single"
							value={`${pageSize}`}
							onValueChange={(value) => Number(value) && (pageSize = Number(value))}
						>
							<Select.Trigger class="w-auto">
								{pageSize ?? 'Select a size'}
							</Select.Trigger>
							<Select.Content>
								<Select.Item value="10">10</Select.Item>
								<Select.Item value="25">25</Select.Item>
								<Select.Item value="50">50</Select.Item>
								<Select.Item value="100">100</Select.Item>
							</Select.Content>
						</Select.Root>
					</div>
					<div class="flex items-center justify-end w-full">
						<Pagination.Root
							count={data.total}
							perPage={data.pageSize}
							page={currentPage}
							onPageChange={(page) => (currentPage = page)}
						>
							{#snippet children({ pages, currentPage })}
								<Pagination.Content class="justify-end w-full">
									<Pagination.Item>
										<Pagination.PrevButton />
									</Pagination.Item>
									{#each pages as page (page.key)}
										{#if page.type === 'ellipsis'}
											<Pagination.Item>
												<Pagination.Ellipsis />
											</Pagination.Item>
										{:else}
											<Pagination.Item>
												<Pagination.Link {page} isActive={currentPage == page.value}>
													{page.value}
												</Pagination.Link>
											</Pagination.Item>
										{/if}
									{/each}
									<Pagination.Item>
										<Pagination.NextButton />
									</Pagination.Item>
								</Pagination.Content>
							{/snippet}
						</Pagination.Root>
					</div>
				</div>
			{/if}
		{:catch error}
			<div
				class="p-8 text-center text-destructive border rounded-lg border-destructive/50 bg-destructive/10"
			>
				<h3 class="font-semibold mb-2">Error loading bookings</h3>
				<p class="text-sm opacity-70 mb-4">{error.message}</p>
				<Button onclick={() => window.location.reload()}>Retry</Button>
			</div>
		{/await}
		{#snippet failed(error: any, reset)}
			<div
				class="p-8 text-center text-destructive border rounded-lg border-destructive/50 bg-destructive/10"
			>
				<h3 class="font-semibold mb-2">Something went wrong</h3>
				<p class="text-sm opacity-70 mb-4">{error.message}</p>
				<Button onclick={reset}>Try again</Button>
			</div>
		{/snippet}
	</svelte:boundary>
</div>

{#await dependenciesPromise}
	<!-- Loading dependencies silently -->
{:then [propsResult, customersResult]}
	<BookingForm
		bind:open={bookingSheetOpen}
		properties={propsResult?.properties}
		customers={customersResult.customers}
	/>
{/await}
